In [1]:
import numpy as np

## Arbitrary analysis of list and numpy array

# Key Differences Table

| Feature         | Python List                    | NumPy Array                     |
|-----------------|--------------------------------|---------------------------------|
| Data Types      | Mixed (any)                    | Homogeneous (all same type)     |
| Math Operations | Not supported elementwise      | Supported & efficient           |
| Performance     | Slower for big data/math       | Faster, uses C under the hood   |
| Functionality   | Flexible, general-purpose      | Specialized for numeric work    |
| Built-in        | Yes                            | No (need `import numpy`)        |
| Memory Usage    | Higher                         | Lower (for large numbers)       |

In [2]:
list = [1, 2, 3, 4]
print(type(list))
print(list)
arr = np.array(list)
print(type(arr))
arr

<class 'list'>
[1, 2, 3, 4]
<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [3]:
# need to check the data consistency
list1 = [1, 2, {'a': 1, 'b': 2}, 4]
print(list1)
arr1 = np.array(list1)
print(type(arr1))
arr1

[1, 2, {'a': 1, 'b': 2}, 4]
<class 'numpy.ndarray'>


array([1, 2, {'a': 1, 'b': 2}, 4], dtype=object)

In [4]:
arr2 = np.array([1, 2, 3, 4, {'a': 1}])
arr2

array([1, 2, 3, 4, {'a': 1}], dtype=object)

In [5]:
arr3 = np.array([1, 2, 3, 4])
arr3

array([1, 2, 3, 4])

In [6]:
arr4 = np.array([1.0, 2.0, 3, 4], dtype=np.float64)
print(arr4)
arr5 = np.array([1.0, 2.0, 3, 4], dtype=np.int32)
print(arr5)

[1. 2. 3. 4.]
[1 2 3 4]


### Doing some math

In [7]:
arr_X1 = np.array([[1,2], [2,3]])
arr_X1

array([[1, 2],
       [2, 3]])

In [8]:
arr_X2 = np.array([[4,5], [6,7]])
arr_X2

array([[4, 5],
       [6, 7]])

In [9]:
sum_result = arr_X1 + arr_X2
sum_result

array([[ 5,  7],
       [ 8, 10]])

#### Element-wise multiplication: Each position i,j in the resulting matrix is the product of elements aij and bij from the same position in the original matrices

In [10]:
print(arr_X1) 
print(arr_X2)
ele_mul_result = arr_X1 * arr_X2
ele_mul_result

[[1 2]
 [2 3]]
[[4 5]
 [6 7]]


array([[ 4, 10],
       [12, 21]])

#### Matrix multipication:  [i]th row of the first matrix and the [j]th column of the second matrix

In [11]:
print(arr_X1) 
print(arr_X2)
mat_mul_result = np.dot(arr_X1, arr_X2)
mat_mul_result

[[1 2]
 [2 3]]
[[4 5]
 [6 7]]


array([[16, 19],
       [26, 31]])