In [2]:
import numpy as np

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        h3 {
            font-family: monospace;
            color: #DCD427
        }
        li {
            font-family: monospace;
            color: #DCD427;
            font-size: 22px
        }
        ul li {
            list-style-type: none;
            padding-left: 0;
            font-size: 18px;
        }
        strong {
            font-size: 18px;
            color: #c55955
        }
    </style>
</head>
<body>
    <h3>Course topic</h3>
    <div>
        <li>random</li>
            <ul>
                <li>1. randint <strong>(one/two dimentional array)</strong></li>
                <li>2. rand <strong>(one/two dimentional array)</strong></li>
                <li>3. randn <strong>(one/two dimentional array)</strong></li>
            </ul>
        <li>reshape <strong>(one/two dimentional array)</strong></li>
        <li>max, min, argmax, argmin</li>
        <li>shape</li>
    </div>
</body>
</html>

In [3]:
np.random.randint(0, 10, size=(3, 4))  # Generates a 3x4 array with random integers between 0 and 10

array([[3, 2, 3, 4],
       [8, 4, 7, 5],
       [6, 9, 6, 4]], dtype=int32)

In [4]:
np.random.randint(0, 100)
# This is a random integer data range from 0 to 100

81

In [5]:
np.random.randint(0, 100, 10)
# This is 10 random integer data range from 0 to 100

array([53, 10, 37, 98,  1, 10, 20, 62, 86, 67], dtype=int32)

In [6]:
np.random.rand(10)

array([0.44996843, 0.391531  , 0.38021621, 0.04492358, 0.75083829,
       0.14325187, 0.02626043, 0.88320736, 0.51850668, 0.95480032])

In [7]:
np.random.rand(5, 4)

array([[0.09516343, 0.32444986, 0.44285211, 0.37057319],
       [0.74736797, 0.19157276, 0.03001841, 0.8786475 ],
       [0.4945721 , 0.96907897, 0.39555452, 0.71145068],
       [0.99999089, 0.43455389, 0.77982367, 0.1404671 ],
       [0.64868359, 0.14003838, 0.43123673, 0.12224325]])

In [8]:
np.random.randn(10)

array([ 0.27536677,  1.9587812 , -1.38841791, -1.95405567,  0.65387367,
        1.56402542,  0.08993709,  0.22047675, -0.85281302,  0.25496646])

In [9]:
np.random.randn(5,4)

array([[ 1.3230725 ,  0.2997064 , -0.3262543 , -0.23838721],
       [-0.08133313,  1.21317749, -0.32484312,  0.35758953],
       [-2.0968818 , -0.67535033,  0.20731861,  0.03604794],
       [-0.64984999, -0.91867337,  1.60022104, -2.17904085],
       [-0.4393893 ,  0.88258207, -0.40245954, -1.07121299]])

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Code+Latin:wght@100..700&family=M+PLUS+Rounded+1c&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&family=Rubik:wght@300..900&display=swap" rel="stylesheet">
    <title>Data science</title>
    <style>
        p {
            font-family: ;
            color: #DCD427;
            font-size: 18px;
        }
    </style>
</head>
<body>
    <div>
        <p>arrange vs randint</p>
    </div>
</body>
</html>

In [10]:
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
randarr = np.random.randint(0, 15, 20)
randarr

array([ 8, 11,  5,  5,  2,  1,  9,  0, 13, 11, 12, 10,  3, 14,  0,  2,  4,
        0, 12, 10], dtype=int32)

In [12]:
reshape_data = arr + randarr
reshape_data

array([ 8, 12,  7,  8,  6,  6, 15,  7, 21, 20, 22, 21, 15, 27, 14, 17, 20,
       17, 30, 29])

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Code+Latin:wght@100..700&family=M+PLUS+Rounded+1c&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&family=Rubik:wght@300..900&display=swap" rel="stylesheet">
    <title>Data science</title>
    <style>
        p {
            font-family: ;
            color: #DCD427;
            font-size: 20px;
        }
    </style>
</head>
<body>
    <div>
        <p>reshape</p>
    </div>
</body>
</html>

In [13]:
reshape_data.reshape(4, 5)

array([[ 8, 12,  7,  8,  6],
       [ 6, 15,  7, 21, 20],
       [22, 21, 15, 27, 14],
       [17, 20, 17, 30, 29]])

In [14]:
reshape_data.reshape(1, 20)

array([[ 8, 12,  7,  8,  6,  6, 15,  7, 21, 20, 22, 21, 15, 27, 14, 17,
        20, 17, 30, 29]])

In [15]:
reshape_data.reshape(2, 10)

array([[ 8, 12,  7,  8,  6,  6, 15,  7, 21, 20],
       [22, 21, 15, 27, 14, 17, 20, 17, 30, 29]])

In [16]:
reshape_data.reshape(10, 2)

array([[ 8, 12],
       [ 7,  8],
       [ 6,  6],
       [15,  7],
       [21, 20],
       [22, 21],
       [15, 27],
       [14, 17],
       [20, 17],
       [30, 29]])

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Code+Latin:wght@100..700&family=M+PLUS+Rounded+1c&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&family=Rubik:wght@300..900&display=swap" rel="stylesheet">
    <title>Data science</title>
    <style>
        p {
            font-family: ;
            color: #DCD427;
            font-size: 20px;
        }
    </style>
</head>
<body>
    <div>
        <p>shape -> this shows the array data dimention</p>
    </div>
</body>
</html>

In [17]:
reshape_data.reshape(4, 5)

array([[ 8, 12,  7,  8,  6],
       [ 6, 15,  7, 21, 20],
       [22, 21, 15, 27, 14],
       [17, 20, 17, 30, 29]])

In [18]:
reshape_data.reshape(4, 5).shape

(4, 5)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
arr.shape

(20,)

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Code+Latin:wght@100..700&family=M+PLUS+Rounded+1c&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&family=Rubik:wght@300..900&display=swap" rel="stylesheet">
    <title>Data science</title>
    <style>
        p {
            font-family: ;
            color: #DCD427;
            font-size: 20px;
        }
    </style>
</head>
<body>
    <div>
        <p>max, min, argmax, argmin</p>
    </div>
</body>
</html>

In [21]:
print(randarr)
randarr.max()

[ 8 11  5  5  2  1  9  0 13 11 12 10  3 14  0  2  4  0 12 10]


np.int32(14)

In [22]:
print(randarr)
randarr.min()

[ 8 11  5  5  2  1  9  0 13 11 12 10  3 14  0  2  4  0 12 10]


np.int32(0)

In [23]:
print(randarr)
randarr.argmax()

[ 8 11  5  5  2  1  9  0 13 11 12 10  3 14  0  2  4  0 12 10]


np.int64(13)

In [24]:
print(randarr)
randarr.argmin()

[ 8 11  5  5  2  1  9  0 13 11 12 10  3 14  0  2  4  0 12 10]


np.int64(7)