<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        h3 {
            font-family: monospace;
            color: #DCD427
        }
        li {
            font-family: monospace;
            color: #DCD427;
            font-size: 22px
        }
        ul li {
            list-style-type: none;
            padding-left: 0;
            font-size: 18px;
        }
        strong {
            font-size: 18px;
            color: #c55955
        }
    </style>
</head>
<body>
    <h3>Course topic</h3>
    <div>
        <li>2D matrix assignment of slicing</li>
    </div>
</body>
</html>

In [3]:
import numpy as np

In [7]:
arr_2D = np.arange(50)
arr_2D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [8]:
arr_2D = np.arange(50).reshape(5, 10)
arr_2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
print(f'4th row, 2nd:5th column: \n {arr_2D[3:4, 1:5]}')

4th row, 2nd:5th column: [[31 32 33 34]]


In [12]:
print(f'2nd:3rd row, 4th:5th column: \n {arr_2D[1:3, 3:5]}')

2nd:3rd row, 4th:5th column: 
 [[13 14]
 [23 24]]
