<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        h3 {
            font-family: monospace;
            color: #DCD427
        }
        li {
            font-family: monospace;
            color: #DCD427;
            font-size: 22px
        }
        ul li {
            list-style-type: none;
            padding-left: 0;
            font-size: 18px;
        }
        strong {
            font-size: 18px;
            color: #c55955
        }
    </style>
</head>
<body>
    <h3>Course topic</h3>
    <div>
        <li>2D matrix</li>
    </div>
</body>
</html>

In [1]:
import numpy as np

In [2]:
arr_2D = np.array([[5,10,15],[20,25,30],[35,40,45],[50,55,60],[65,70,75]])
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60],
       [65, 70, 75]])

In [3]:
# Row information
print(arr_2D[0])
print(arr_2D[1])
print(arr_2D[2])

[ 5 10 15]
[20 25 30]
[35 40 45]


In [4]:
# shape output are coming in tupple format, so need to extract the tupple output and use as range
print(arr_2D.shape)
print(arr_2D.shape[0])
print(arr_2D.shape[1])

(5, 3)
5
3


In [5]:
for i in range(arr_2D.shape[0]):
    for j in range(arr_2D.shape[1]):
        print(f'arr_2D[{i}][{j}]: {arr_2D[i][j]}')

arr_2D[0][0]: 5
arr_2D[0][1]: 10
arr_2D[0][2]: 15
arr_2D[1][0]: 20
arr_2D[1][1]: 25
arr_2D[1][2]: 30
arr_2D[2][0]: 35
arr_2D[2][1]: 40
arr_2D[2][2]: 45
arr_2D[3][0]: 50
arr_2D[3][1]: 55
arr_2D[3][2]: 60
arr_2D[4][0]: 65
arr_2D[4][1]: 70
arr_2D[4][2]: 75


In [6]:
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60],
       [65, 70, 75]])

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Code+Latin:wght@100..700&family=M+PLUS+Rounded+1c&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&family=Rubik:wght@300..900&display=swap" rel="stylesheet">
    <title>Data science</title>
    <style>
        div {
            font-family: 'Roboto Mono';
        }
        p {
            color: #DCD427;
            font-size: 18px;
        }
        .note {
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div>
        <p>slicing 1D/2D</p>
        <p class='note'>array[start:stop-1] - returns elements from start index up to, but not including, stop index</p>
    </div>
</body>
</html>

In [7]:
print(f'left-upper-corner: \n {arr_2D[0:2,0:2]}')
print(f'right-upper-corner: \n {arr_2D[0:2,1:3]}')
print(f'left-below-corner: \n {arr_2D[3:5,0:2]}')
print(f'right-below-corner: \n {arr_2D[3:5,1:3]}')

left-upper-corner: 
 [[ 5 10]
 [20 25]]
right-upper-corner: 
 [[10 15]
 [25 30]]
left-below-corner: 
 [[50 55]
 [65 70]]
right-below-corner: 
 [[55 60]
 [70 75]]


In [8]:
print(f'1st two rows: \n {arr_2D[0:2,0:3]}')
print(f'last two rows: \n {arr_2D[3:5,0:3]}')
print(f'1st two columns: \n {arr_2D[0:5,0:2]}')
print(f'last two columns: \n {arr_2D[0:5,1:3]}')

1st two rows: 
 [[ 5 10 15]
 [20 25 30]]
last two rows: 
 [[50 55 60]
 [65 70 75]]
1st two columns: 
 [[ 5 10]
 [20 25]
 [35 40]
 [50 55]
 [65 70]]
last two columns: 
 [[10 15]
 [25 30]
 [40 45]
 [55 60]
 [70 75]]


In [9]:
print(f'arr_2D: \n {arr_2D[0:5, 0:3]}')
print(f'arr_2D 1st row: \n {arr_2D[0:1, 0:3]}')
print(f'arr_2D 2nd row: \n {arr_2D[1:2, 0:3]}')
print(f'arr_2D 5th row: \n {arr_2D[4:5, 0:3]}')
print(f'arr_2D 1st column: \n {arr_2D[0:5, 0:1]}')
print(f'arr_2D 2nd column: \n {arr_2D[0:5, 1:2]}')
print(f'arr_2D 3rd column: \n {arr_2D[0:5, 2:3]}')

arr_2D: 
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]
 [65 70 75]]
arr_2D 1st row: 
 [[ 5 10 15]]
arr_2D 2nd row: 
 [[20 25 30]]
arr_2D 5th row: 
 [[65 70 75]]
arr_2D 1st column: 
 [[ 5]
 [20]
 [35]
 [50]
 [65]]
arr_2D 2nd column: 
 [[10]
 [25]
 [40]
 [55]
 [70]]
arr_2D 3rd column: 
 [[15]
 [30]
 [45]
 [60]
 [75]]


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Code+Latin:wght@100..700&family=M+PLUS+Rounded+1c&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&family=Rubik:wght@300..900&display=swap" rel="stylesheet">
    <title>Data science</title>
    <style>
        div {
            font-family: 'Roboto Mono';
        }
        p {
            color: #DCD427;
            font-size: 18px;
        }
        .note {
            font-size: 14px;
        }
        strong {
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div>
        <p>slicing 2D</p>
        <p class='note'>Row data show: array_data[i], <strong>i = 0, 1, 2, 3</strong></p>
        <p class='note'>Column data show: array_data[:, j], <strong>i = 0, 1, 2, 3</strong></p>
    </div>
</body>
</html>

In [16]:
arr_2D = np.arange(0,28).reshape(7,4)
arr_2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [ ]:
# All ROW data
for i in range(arr_2D.shape[0]):
    print(f'Row {i} data: {arr_2D[i]}')

Row 0 data: [0 1 2 3]
Row 1 data: [4 5 6 7]
Row 2 data: [ 8  9 10 11]
Row 3 data: [12 13 14 15]
Row 4 data: [16 17 18 19]
Row 5 data: [20 21 22 23]
Row 6 data: [24 25 26 27]


In [18]:
# All COLUMN data
for j in range(arr_2D.shape[1]):
    print(f'Column {j} data: {arr_2D[:, j]}')

Column 0 data: [ 0  4  8 12 16 20 24]
Column 1 data: [ 1  5  9 13 17 21 25]
Column 2 data: [ 2  6 10 14 18 22 26]
Column 3 data: [ 3  7 11 15 19 23 27]
