<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        h3 {
            font-family: monospace;
            color: #DCD427
        }
        li {
            font-family: monospace;
            color: #c55955;
            font-size: 18px
            list-style-type: none;
            padding-left: 0;
        }
    </style>
</head>
<body>
    <h3>Course topic</h3>
    <div>
        <li>Conditional array</li>
    </div>
</body>
</html>

In [11]:
import numpy as np

In [12]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [14]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [15]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [16]:
arr_rand = np.random.randint(1, 10, 10)
arr_rand

array([2, 6, 8, 9, 1, 1, 6, 7, 9, 3], dtype=int32)

In [17]:
arr_rand[arr_rand > 6]

array([8, 9, 7, 9], dtype=int32)

In [18]:
arr_rand[arr_rand < 6]

array([2, 1, 1, 3], dtype=int32)