<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        h3 {
            font-family: monospace;
            color: #DCD427
        }
        li {
            font-family: monospace;
            color: #DCD427;
            font-size: 22px
        }
        ul li {
            list-style-type: none;
            padding-left: 0;
            font-size: 18px;
        }
        strong {
            font-size: 18px;
            color: #c55955
        }
    </style>
</head>
<body>
    <h3>Course topic</h3>
    <div>
        <li>NumPy Indexing, Selection, Copy</li>
    </div>
</body>
</html>

In [3]:
import numpy as np

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Code+Latin:wght@100..700&family=M+PLUS+Rounded+1c&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&family=Rubik:wght@300..900&display=swap" rel="stylesheet">
    <title>Data science</title>
    <style>
        p {
            font-family: ;
            color: #DCD427;
            font-size: 18px;
        }
    </style>
</head>
<body>
    <div>
        <p>indexing</p>
    </div>
</body>
</html>

In [4]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[4]

np.int64(4)

In [31]:
arr_rand = np.random.randint(1,10, 10)
arr_rand

array([3, 9, 9, 8, 3, 3, 1, 9, 5, 6], dtype=int32)

In [33]:
print(arr_rand[2])
print(arr_rand[8])

9
5


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Code+Latin:wght@100..700&family=M+PLUS+Rounded+1c&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&family=Rubik:wght@300..900&display=swap" rel="stylesheet">
    <title>Data science</title>
    <style>
        div {
            font-family: 'Roboto Mono';
        }
        p {
            color: #DCD427;
            font-size: 18px;
        }
        .note {
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div>
        <p>slicing 1D</p>
        <p class='note'>array[start:stop-1] - returns elements from start index up to, but not including, stop index</p>
    </div>
</body>
</html>

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[0:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[5:]

array([5, 6, 7, 8, 9])

In [10]:
arr[:5]

array([0, 1, 2, 3, 4])

In [29]:
arr = np.arange(0, 10)
print('arr: ', arr)
arr[:5]
arr[:5] = 100
print('arr: ', arr)
slice_of_arr = arr[:6]
print('slice_of_arr: ', slice_of_arr)
slice_of_arr[:] = 0
print('slice_of_arr: ', slice_of_arr)
print('arr: ', arr)

arr:  [0 1 2 3 4 5 6 7 8 9]
arr:  [100 100 100 100 100   5   6   7   8   9]
slice_of_arr:  [100 100 100 100 100   5]
slice_of_arr:  [0 0 0 0 0 0]
arr:  [0 0 0 0 0 0 6 7 8 9]


#### Copy functionalities

In [30]:
print('arr: ', arr) # arr is also modified because slice_of_arr is a view of arr
arr_copy = arr.copy() # arr_copy is a copy of arr, not a view
print('arr_copy: ', arr_copy) # Modifying arr_copy will not affect arr
print('arr: ', arr) # arr remains unchanged
arr_copy[:7] = 100 # Modifying arr_copy does not affect arr
print('arr_copy: ', arr_copy) # arr_copy is modified
print('arr: ', arr) # arr remains unchanged
arr_copy[:] = 100 # Modifying arr_copy does not affect arr
print('arr_copy: ', arr_copy) # arr_copy is modified
print('arr: ', arr) # arr remains unchanged

arr:  [0 0 0 0 0 0 6 7 8 9]
arr_copy:  [0 0 0 0 0 0 6 7 8 9]
arr:  [0 0 0 0 0 0 6 7 8 9]
arr_copy:  [100 100 100 100 100 100 100   7   8   9]
arr:  [0 0 0 0 0 0 6 7 8 9]
arr_copy:  [100 100 100 100 100 100 100 100 100 100]
arr:  [0 0 0 0 0 0 6 7 8 9]
